project:
  type: website
  output-dir: docs
  resources: 
    - "/media/profile.png"
    - "/media/quarto.png"
    - "/media/*"

website:
  title: "Demo Website"
  site-url: https://mohitshrestha.github.io
  description: "Demo Website made with Quarto along with Blog funtionality"
  favicon: /media/profile.png
  google-analytics: "G-X51FE05DVC"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts.qmd
      - text: DataViz Portfolio
        href: dataviz_portfolio.qmd
      - text: R and Python Analysis
        menu: 
          - text: R Analysis
            href: posts/example_r_codes/index.qmd
          - text: Python Analysis
            href: posts/example_python_codes/index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        text: Github
        href: https://github.com/MohitShrestha
      - icon: rss
        text: RSS
        href: posts.xml
  page-footer:
    background: light
    left: |
      [Demo Website](https://mohitshrestha.github.io/demo_website) © {{< var website.copyright_year >}} by [Mohit Shrestha](https://mohitshrestha.com.np/) <br> Licensed under <img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" width="25"/> <img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" width="25"/> [CC BY 4.0 (Creative Commons Attribution 4.0 International)](/license_cc-by.qmd)
    right: |
      Made with ❤️ and [![](media/quarto.png){fig-alt="Quarto Logo" width="84" height="18"}](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var website.github_url >}})
  repo-url: https://www.github.com/mohitshrestha/demo_website
  repo-actions: [edit, issue]

format:
  html:
    theme: 
        light: litera
        dark: darkly
    css: styles.css
    toc: true

editor: visual

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes